# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15YpV-Ssi2p63CaMAz_Ytc4T-RHKw8bVT
"""

# Define the function to translate DNA to protein
def dna_to_protein(dna):
    # Define the genetic code (codon to amino acid mapping)
    genetic_code = {
        'ATG': 'M', 'TTT': 'F', 'TTC': 'F', 'TTA': 'L', 'TTG': 'L',
        'TCT': 'S', 'TCC': 'S', 'TCA': 'S', 'TCG': 'S', 'TAT': 'Y',
        'TAC': 'Y', 'TAA': '*', 'TAG': '*', 'TGT': 'C', 'TGC': 'C',
        'TGA': '*', 'TGG': 'W', 'CTT': 'L', 'CTC': 'L', 'CTA': 'L',
        'CTG': 'L', 'CCT': 'P', 'CCC': 'P', 'CCA': 'P', 'CCG': 'P',
        'CAT': 'H', 'CAC': 'H', 'CAA': 'Q', 'CAG': 'Q', 'CGT': 'R',
        'CGC': 'R', 'CGA': 'R', 'CGG': 'R', 'ATT': 'I', 'ATC': 'I',
        'ATA': 'I', 'ATG': 'M', 'ACT': 'T', 'ACC': 'T', 'ACA': 'T',
        'ACG': 'T', 'AAT': 'N', 'AAC': 'N', 'AAA': 'K', 'AAG': 'K',
        'AGT': 'S', 'AGC': 'S', 'AGA': 'R', 'AGG': 'R', 'GTT': 'V',
        'GTC': 'V', 'GTA': 'V', 'GTG': 'V', 'GCT': 'A', 'GCC': 'A',
        'GCA': 'A', 'GCG': 'A', 'GAT': 'D', 'GAC': 'D', 'GAA': 'E',
        'GAG': 'E', 'GGT': 'G', 'GGC': 'G', 'GGA': 'G', 'GGG': 'G'
    }

    protein = ""
    # Translate the DNA sequence in codons (3 bases at a time)
    for i in range(0, len(dna), 3):
        codon = dna[i:i+3]
        if codon in genetic_code:
            protein += genetic_code[codon]
        else:
            # Handle cases where the codon is not in the genetic code
            protein += '?'  # Or some other indicator for an unknown codon
    return protein

# Define a DNA sequence as a string
dna_sequence= "ATGGCCATTGTAATGGGCCGCTGAAAGGGTGCCCGATAG"

# Call the dna_to_protein function to translate the DNA into a protein sequence
protein = dna_to_protein(dna_sequence)

# Print the resulting protein sequence
print(protein)

def hamming_distance(str1, str2):
    """
    Calculates the Hamming distance between two strings.
    If strings are of different lengths, the extra characters count as differences.

    Parameters:
        str1 (str): First string
        str2 (str): Second string

    Returns:
        int: Hamming distance (number of differing characters)
    """

    # Convert both strings to lowercase
    str1 = str1.lower()
    str2 = str2.lower()

    # Find the minimum length to compare characters position-wise
    min_len = min(len(str1), len(str2))

    # Count differences character by character
    distance = sum(1 for i in range(min_len) if str1[i] != str2[i])

    # Add the difference in length (remaining characters are all mismatches)
    distance += abs(len(str1) - len(str2))

    return distance


# Example usage
slack_username = "Keola"
twitter_handle = "keola2j"

result = hamming_distance(slack_username, twitter_handle)
print("Hamming Distance:", result)

import pandas as pd

url = "https://raw.githubusercontent.com/HackBio-Internship/2025_project_collection/refs/heads/main/Python/Dataset/hbr_uhr_top_deg_normalized_counts.csv"
# Read the CSV file directly from the link
df = pd.read_csv(url)

print(df.head())

# Set the 'Unnamed: 0' column as row labels
df.set_index("Unnamed: 0", inplace=True)

import matplotlib.pyplot as plt
plt.figure(figsize=(8, 6))  # Set figure size (width, height)

# Plot heatmap: imshow() displays the data as a colored matrix
plt.imshow(df, aspect="auto", cmap="Blues")  # cmap="Blues" sets the blue gradient

# Add a color bar to show the scale of expression values
plt.colorbar(label="Normalized Expression")

# Set x-axis tick labels (sample names)
plt.xticks(range(len(df.columns)), df.columns, rotation=45)

# Set y-axis tick labels (gene names)
plt.yticks(range(len(df.index)), df.index)

# Add title for clarity
plt.title("Heatmap of Top Differentially Expressed Genes (HBR vs UHR)")

# Prevent labels from overlapping
plt.tight_layout()

# Display heatmap
plt.show()

import pandas as pd

url = "https://raw.githubusercontent.com/HackBio-Internship/2025_project_collection/refs/heads/main/Python/Dataset/hbr_uhr_deg_chr22_with_significance.csv"
# Read the CSV file directly from the link
df = pd.read_csv(url)

print(df.head())

# Map colors
color_map = {
    "up": "green",      # Upregulated genes
    "down": "orange",   # Downregulated genes
    "ns": "grey"        # Not significant
    }

# Assign colors
df["color"] = df["significance"].map(color_map)

# Scatter plot (log2FoldChange vs -log10 adjusted p-value)
plt.figure(figsize=(8, 6))
plt.scatter(df["log2FoldChange"], df["-log10PAdj"],
            c=df["color"], s=25, alpha=0.7)

# Add dashed vertical threshold lines at log2FC = ±1
plt.axvline(x=1, linestyle="--", color="black")
plt.axvline(x=-1, linestyle="--", color="black")

# Axis labels & plot title
plt.xlabel("log2(Fold Change)")
plt.ylabel("-log10(Adjusted P-value)")
plt.title("Volcano Plot - Differential Gene Expression")

plt.show()

import pandas as pd

url = "https://raw.githubusercontent.com/HackBio-Internship/2025_project_collection/refs/heads/main/Python/Dataset/data-3.csv"
# Read the CSV file directly from the link
df = pd.read_csv(url)

print(df.head())

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
sns.scatterplot(data=df, x="radius_mean", y="texture_mean", hue="diagnosis")

plt.title("Scatter Plot: Texture Mean vs Radius Mean")
plt.xlabel("Radius Mean")
plt.ylabel("Texture Mean")
plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Select key features from the dataset for correlation analysis
features = [
    "radius_mean", "texture_mean", "perimeter_mean",
    "area_mean", "smoothness_mean", "compactness_mean"
]

# Compute the correlation matrix
# corr() calculates the pairwise correlation between selected numeric features
corr_matrix = df[features].corr()

# Step 3: Plot the correlation heatmap
plt.figure(figsize=(8,6))  # Set figure size for better visibility

sns.heatmap(
    corr_matrix,
    annot=True,      # Display correlation values in each cell
    fmt=".2f",       # Format the values to two decimal places
    cmap="Blues",    # Color palette
    square=True      # Make cells square-shaped
)

# Add title for the heatmap
plt.title("Correlation Heatmap of Key Breast Cancer Features")

# Display the heatmap
plt.show()

import matplotlib.pyplot as plt

# Separate malignant and benign for coloring
malignant = df[df["diagnosis"] == "M"]
benign = df[df["diagnosis"] == "B"]

plt.figure(figsize=(8,6))

# Scatter plot
plt.scatter(malignant["compactness_mean"], malignant["smoothness_mean"], label="Malignant")
plt.scatter(benign["compactness_mean"], benign["smoothness_mean"], label="Benign")

# Axis labels
plt.xlabel("Compactness (mean)")
plt.ylabel("Smoothness (mean)")

# Title
plt.title("Scatter Plot: Smoothness vs Compactness")

# Gridlines
plt.grid(True, linestyle="--", alpha=0.5)

# Legend (M / B)
plt.legend(title="Diagnosis")

# Show plot
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(8,6))

# KDE curves for malignant and benign
sns.kdeplot(data=df[df["diagnosis"] == "M"]["area_mean"], label="Malignant", fill=True , linewidth=2)
sns.kdeplot(data=df[df["diagnosis"] == "B"]["area_mean"], label="Benign", fill=True, linewidth=2)

# Axis labels
plt.xlabel("Area (mean)")
plt.ylabel("Density")

# Title and legend
plt.title("Density Plot of Tumor Area (Mean) by Diagnosis")
plt.legend(title="Diagnosis")

plt.show()

